version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:3000"
    restart: always
    env_file:
      - ./backend/.env
    networks:
      - my-network

networks:
  my-network:
    external: true