version: '3.8'

services:
  frontend:
    build: .
    container_name: frontend
    ports:
      - "81:81"
    restart: always
    networks:
      - my_network

networks:
  my_network:
    external: true