version: '3.8'

services:
  frontend:
    build: .
    container_name: frontend
    ports:
      - "80:80"
    restart: always
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true