version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "81:81"
    restart: always
    networks:
      - dokploy-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.frontend-app.rule=Host(egeball.com)
      - traefik.http.routers.frontend-app.entrypoints=web
      - traefik.http.services.frontend-app.loadbalancer.server.port=81

networks:
  dokploy-network:
    external: true