version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    restart: always
    env_file:
      - .env
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true