version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    restart: always
    networks:
      - my-network

networks:
  my-network:
    external: true