version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "81:81"
    restart: always
    volumes:
      - ./nginx/cert.pem:/etc/cert.pem
      - ./nginx/key.pem:/etc/key.pem
    networks:
      - my-network

networks:
  my-network:
    external: true