version: '3.8'

services:
  backend:
    build: .
    container_name: backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    restart: always
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true